### PR TITLE
fix: update header hide only at mobile

### LINKED ISSUE #245: Lists: some ordered lists start on a new line
I think the Carbon lists might have made it worse. The lists still tuck under the numbers, but now they also sometimes start on a new line.  

https://gatsby-theme-carbon.now.sh/guides/shadowing

AE213798-2416-4F15-A6FC-C45EB1770453

### PR DESCRIPTION
**Pull request by alisonjoseph**
closes #245 

Header only hides at mobile, and only when there are tabs present. 

I think this is the functionality we want. @vpicone @jeanservaas

### CODE REVIEW

File: packages/gatsby-theme-carbon/src/util/hooks/useScrollDirection.js [hunk 1]
```diff
@@ -9,10 +9,10 @@ const useScrollDirection = () => {
   const windowSize = useWindowSize();
 
   useEffect(() => {
-    const pastPageHeader = y > 240;
-    const isDesktop = windowSize.innerWidth > 1056;
+    const pastPageHeader = y > 290;
+    // const isDesktop = windowSize.innerWidth > 1056;
```
Comment (alisonjoseph) [inline packages/gatsby-theme-carbon/src/util/hooks/useScrollDirection.js]: am I breaking anything else by removing this @vpicone

Comment (vpicone) [reply packages/gatsby-theme-carbon/src/util/hooks/useScrollDirection.js]: nah, just gonna clean something up rq
