### PR TITLE
fix(EditLink): Adds branch option to edit url

### LINKED ISSUE #455: Edit on Github branch
## Detailed description

Should add an optional node to the repository config to set the branch you would like to be edited.

> Describe in detail the issue you're having.

Configured the edit in github for my site, but when I click on the link it hits a 404, because my repository is set to host the master branch as the gh-pages site.  The repository's default branch is set to develop.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected to hit the actual file in the develop branch so that I can actually edit that file in github.

> What browser are you working in?

Chrome

## Steps to reproduce the issue

1. Create a [User or organization site](https://pages.github.com/) using gh-pages
1. Set the default branch of your repository to be something other than master (my case develop)
1.   image
1. Create the starte gatsby-theme-carbon site
1. Configure the repository node of the gatsby-config.js
1. deploy your site to master
1. Run the site.
1. click on any edit on github link

## Additional information

- Screenshots or code
- Notes

### PR DESCRIPTION
**Pull request by ENG618**
fixes carbon-design-system/gatsby-theme-carbon#455

Closes #455 

Adds a configuration option to specify what branch the `EditLink` should point to when opening github.

#### Changelog

**New**

- N/A

**Changed**

- config options for repository not accepts branch

**Removed**

- N/A

### CODE REVIEW

File: packages/gatsby-theme-carbon/gatsby-config.js [hunk 1]
```diff
@@ -14,6 +14,7 @@ module.exports = themeOptions => {
     repository = {
       baseUrl: '',
       subDirectory: '',
+      branch: 'master',
```
Comment (ENG618) [inline packages/gatsby-theme-carbon/gatsby-config.js]: @vpicone wouldn't this be setting the default `themeOptions` to master?

Comment (vpicone) [reply packages/gatsby-theme-carbon/gatsby-config.js]: I'm confused by the docs update

>Even if you have no `subDirectory` an empty string `''` must be supplied.

Can you elaborate on that? Unfortunately we can't force folks to add a theme option without it being a breaking change/major release.

Comment (ENG618) [reply packages/gatsby-theme-carbon/gatsby-config.js]: So to clarify this is a pre-existing issue.  They are not required to put in that theme option unless they want the edit on Github link.  In which case you would be required to supply all nodes of the `repository` option.

This was something I found because my site does not have a subdirectory (is a user site) and if I do not have that `subDirectory: ''` the site does not build with the following error.

```
 ERROR #85907  GRAPHQL

There was an error in your GraphQL query:

- Unknown field 'subDirectory' on type 'SiteSiteMetadataRepository'.

File: node_modules/gatsby-theme-carbon/src/components/EditLink/EditLink.js

⠙ extract queries from components
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Maybe my documentation addition needs to be reworded, and I can open another bug issue.

**Comment by vpicone** [comment]
@jnm2377 let me know if you have any questions on reviewing
