### PR TITLE
fix(PageTabs): update current tab regex 

### LINKED ISSUE #884: tab navigation is broken when section title contains tab title
## Detailed description
On https://pages.github.ibm.com/ai-applications/design/conceptual-model/model

the `learn more` and `overview` tabs are broken: 

It’s generating urls of
.../design/conceptual-learn-more/model
but it should be
.../design/conceptual-model/learn-more

so it 404s

### LINKED ISSUE #960: Problem with a tab name that has an apostrophe in it
## Detailed description

> Describe in detail the issue you’re having.
tabs:
  [
    'Overview',
    'Welcome page',
    'Whats new',
  ]
Results in an error on the page and the tab list getting displayed as plain text

Using the HTML code for ' instead of the character results in the tab name being displayed as What&#39; New

> What did you expect to happen? What happened instead? What would you like to see changed?
I would like to be able to use an apostrophe in the tab name.

> What browser are you working in?
Firefox

## Steps to reproduce the issue

1. Create a page that has a tab that as an apostrophe in the name.

## Additional information

- Screenshots or code
- Notes

### PR DESCRIPTION
**Pull request by jnm2377**
Closes #884 
Closes #960 

- fixes current tab regex so it's not replacing incomplete slugs
- removes apostrophes from tabs/slugs 
- adds documentation for tabs with `'`
- testing example added under `> Guides > Testing tabs` and `> Guides > Navigation > Nav`

**Note: Do not merge after approval, need to remove testing pages before merging**

### CODE REVIEW

File: packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js [hunk 1]
```diff
@@ -15,15 +15,21 @@ import {
 export default class PageTabs extends React.Component {
   render() {
     const { tabs, slug } = this.props;
-    const currentTab = slug.split('/').filter(Boolean).slice(-1)[0];
+    const newSlug = slug.replace(/[’']/g, ''); // removes any apostrophes from slug
```
Comment (vpicone) [inline packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:18]: While this solves the apostrophe problem, we probably wanna look for a solution that works for any punctuation/odd characters

File: packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js [hunk 2]
```diff
@@ -15,15 +15,21 @@ import {
...
+    const currentTab = newSlug.split('/').filter(Boolean).slice(-1)[0];
 
     const pageTabs = tabs.map((tab) => {
-      const slugifiedTab = slugify(tab, { lower: true });
+      const tempTab = tab.replace(/[’']/g, ''); // removes any apostrophes from tab
+      const slugifiedTab = slugify(tempTab, { lower: true });
```
Comment (vpicone) [inline packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:23]: Slugify has a [`strict` option](https://www.npmjs.com/package/slugify#options) that removes any punctuation/special characters

From a quick test, it strips out the apostrophe so it would match the yaml/filename after processing. I think that should remove the need for the temp tab all together maybe.

File: packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js [hunk 3]
```diff
@@ -15,15 +15,21 @@ import {
...
       const selected = slugifiedTab === currentTab;
-      const currentTabRegex = new RegExp(`${currentTab}(?!-)`);
+      const currentTabRegex = new RegExp(`(?<!-)${currentTab}(?!-)`);
```
Comment (vpicone) [inline packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:25]: While this works for `/conceptual-model/model` it wouldn't solve the issue for something like `/navigation/nav`. We'd still end up replacing the first instance of `nav` and get broken urls.

What if instead, we use a `$` to indicate the end of the string (while allowing for an optional trailing slash)?

```suggestion
      const currentTabRegex = new RegExp(`${currentTab}/?$`);
```

**Review by vpicone — CHANGES_REQUESTED** [review]

File: packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js (hunk 3 above)
Comment (jnm2377) [reply packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:25]: Good point @vpicone. Would it still work if the url is pointing to a specific section of the page and the tab isn't necessarily the end of the string? i.e. `/conceptual-model/model/#section-of-page`

Comment (vpicone) [reply packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:25]: @jnm2377 good question, hash links don't work if there's a slash in between though ( so it'd be `/conceptual-model/model#section-of-page` and `/conceptual-model/model#section-of-page/`) I'm not even sure they work with a trailing slash.

Let me know if it doesn't work with section links and we can brainstorm

Comment (jnm2377) [reply packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:25]: this example I was just looking at has a slash in between: https://www.ibm.com/design/language/iconography/pictograms/contribute/#export-svgs-from-adobe-illustrator

Comment (vpicone) [reply packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:25]: @jnm2377 oh wow sure enough maybe this is a server setting? Good catch. We can get around this by looking for _either_ a hashtag _or_ the end of the line. I'll edit my suggestion.

Comment (vpicone) [reply packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:25]: @jnm2377 updated to add an optional group for hash links

Comment (jnm2377) [reply packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js]: Seems to be working. I added another testing example under `Guides > Navigation > Nav`

File: packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js (hunk 1 above)
Comment (jnm2377) [reply packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:18]: Hmm.. @vpicone we can add more characters into this regex. But wondering if there would be an easier way to say "replace any character that's not a letter, number or `-`" besides listing all the possible characters.. I'll look into it. Regex's aren't my strong suit but I'll google it haha

Comment (jnm2377) [reply packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js]: updated!

File: packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js [hunk 4]
```diff
@@ -15,12 +15,15 @@ import {
 export default class PageTabs extends React.Component {
   render() {
     const { tabs, slug } = this.props;
-    const currentTab = slug.split('/').filter(Boolean).slice(-1)[0];
+    const newSlug = slug.replace(/[^a-zA-Z0-9-\/]/g, ''); // removes any characters that aren't letters, numbers or dash/fwd slash
```
Comment (vpicone) [inline packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:18]: Do we still need this? If so, we could use slugify w/ the same settings to remove the stuff so we can guarantee we're comparing apples to apples.

**Review by vpicone — COMMENTED** [review]
qq

File: packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js (hunk 4 above)
Comment (jnm2377) [reply packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:18]: So slugify the slug? This part is for the initial landing tab, the line where we slugify the tab name is just for when we're looking for what to replace when switching tabs, so we still need something to replace the characters on the initial tab. Are you suggesting something like:
`const newSlug = slugify(slug, { lower: true, strict: true });`

Comment (jnm2377) [reply packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:18]: ^ hope that makes sense regarding the slug v tab regex @vpicone

Comment (vpicone) [reply packages/gatsby-theme-carbon/src/components/PageTabs/PageTabs.js:18]: @jnm2377 the slug comes from `location.pathname` in the Default template so it should already be a valid URL. After the update to use strict slugify below, I'm not sure what links they would click that could take them to a URL with special characters in it.

**Review by vpicone — APPROVED** [review]
🚀

**Review by sstrubberg — APPROVED** [review]
That's some legit regex'ing 🎉
